# vi docker-compose.yml
version: "3.3"
services:
  mongo:
    ports:
      - "27017:27017"
    image: mongo
    container_name: realtime-messenger-mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=lamierda2
